<script setup>
import {computed,nextTick,onBeforeUnmount,onMounted,reactive,ref} from 'vue'
import {requestJSON} from '../api'

const loading=ref(true),busy=ref(false),testing=ref(false),message=ref(''),error=ref('')
const profiles=ref([]),nodes=ref([]),workflow=ref(null),workflowFile=ref(''),job=ref(null),reference=ref(null),referenceAudio=ref(null),mappingPanel=ref(null),profileNameInput=ref(null),creatingProfile=ref(false)
const connection=reactive({name:'本机 ComfyUI',base_url:'http://127.0.0.1:8188',websocket_url:'',prompt_path:'/prompt',history_path:'/history/{prompt_id}',upload_path:'/upload/image',view_path:'/view',interrupt_path:'/interrupt'})
const emptyBinding=()=>({node_id:'',input_name:''})
const resolutionOptions={480:{key:'480p',width:854,height:480},720:{key:'720p',width:1280,height:720},1080:{key:'1080p',width:1920,height:1080}}
const profile=reactive({id:'',name:'',kind:'video',resolution_preset:'720p',default_width:1280,default_height:720,default_seed:-1,mappings:{prompt:emptyBinding(),image:emptyBinding(),audio:emptyBinding(),duration:emptyBinding(),width:emptyBinding(),height:emptyBinding(),seed:emptyBinding(),output_node_id:'',duration_mode:'frames',fps:24,frame_divisor:1,frame_remainder:0}})
const run=reactive({profile_id:'',prompt:'',duration:5,width:1280,height:720,seed:-1})
let pollTimer=null
const selectedProfile=computed(()=>profiles.value.find(item=>item.id===run.profile_id))
function clearNotice(){message.value='';error.value=''}
function hydrateConnection(value){Object.assign(connection,value||{})}
function resetProfile(){Object.assign(profile,{id:'',name:'',kind:'video',resolution_preset:'720p',default_width:1280,default_height:720,default_seed:-1,mappings:{prompt:emptyBinding(),image:emptyBinding(),audio:emptyBinding(),duration:emptyBinding(),width:emptyBinding(),height:emptyBinding(),seed:emptyBinding(),output_node_id:'',duration_mode:'frames',fps:24,frame_divisor:1,frame_remainder:0}});nodes.value=[];workflow.value=null;workflowFile.value='';creatingProfile.value=false}
function inferResolutionPreset(width,height){const long=Math.max(Number(width)||0,Number(height)||0),short=Math.min(Number(width)||0,Number(height)||0);return Object.values(resolutionOptions).find(item=>item.width===long&&item.height===short)?.key||'custom'}
function applyResolutionPreset(){const selected=Object.values(resolutionOptions).find(item=>item.key===profile.resolution_preset);if(!selected)return;profile.default_width=selected.width;profile.default_height=selected.height}
const resolutionSummary=computed(()=>`${Math.max(profile.default_width,profile.default_height)} × ${Math.min(profile.default_width,profile.default_height)}（横屏） · ${Math.min(profile.default_width,profile.default_height)} × ${Math.max(profile.default_width,profile.default_height)}（竖屏）`)
async function newProfile(){resetProfile();creatingProfile.value=true;clearNotice();message.value='已进入新建预设：请读取最近一次运行，或导入 API 工作流。';await nextTick();mappingPanel.value?.scrollIntoView({behavior:'smooth',block:'start'});profileNameInput.value?.focus()}
async function load(){loading.value=true;clearNotice();try{const data=await requestJSON('/api/comfyui');hydrateConnection(data.connection);profiles.value=data.profiles||[];if(!run.profile_id&&profiles.value.length)run.profile_id=profiles.value[0].id}catch(e){error.value=e.message}finally{loading.value=false}}
async function saveConnection(){busy.value=true;clearNotice();try{hydrateConnection(await requestJSON('/api/comfyui/connection',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(connection)}));message.value='连接配置已保存。'}catch(e){error.value=e.message}finally{busy.value=false}}
async function testConnection(){testing.value=true;clearNotice();try{const data=await requestJSON('/api/comfyui/connection/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(connection)});message.value=`连接成功 · ${data.node_count} 个节点 · ${data.latency_ms} ms`}catch(e){error.value=e.message}finally{testing.value=false}}
function graphOf(value){return value?.prompt&&typeof value.prompt==='object'&&!Array.isArray(value.prompt)?value.prompt:value}
function summarize(value){const graph=graphOf(value);if(!graph||Array.isArray(graph)||Array.isArray(graph.nodes))throw new Error('这是画布工作流，请在 ComfyUI 开启开发者模式后导出 API 格式 JSON。');const list=Object.entries(graph).filter(([,node])=>node&&typeof node==='object'&&node.class_type).map(([id,node])=>({id:String(id),class_type:String(node.class_type),title:String(node._meta?.title||node.class_type||id),inputs:Object.keys(node.inputs||{})}));if(!list.length)throw new Error('没有识别到 API 工作流节点。');return {graph,list}}
function guessBinding(pattern,inputPatterns=[]){const found=nodes.value.find(node=>pattern.test(`${node.title} ${node.class_type}`)&&node.inputs.some(input=>inputPatterns.some(p=>p.test(input))));if(!found)return emptyBinding();const input=found.inputs.find(value=>inputPatterns.some(p=>p.test(value)))||'';return {node_id:found.id,input_name:input}}
function autoMap(){profile.mappings.prompt=guessBinding(/text|prompt|string|conditioning/i,[/text|prompt|string|value/i]);profile.mappings.image=guessBinding(/loadimage|image/i,[/^image$/i]);profile.mappings.audio=guessBinding(/loadaudio|audio/i,[/^audio$/i]);profile.mappings.duration=guessBinding(/duration|length|frame|primitive|math|时长/i,[/duration|length|frame|value/i]);profile.mappings.width=guessBinding(/resolution|size|latent|video|minimax/i,[/^width$/i]);profile.mappings.height=guessBinding(/resolution|size|latent|video|minimax/i,[/^height$/i]);profile.mappings.seed=guessBinding(/sampler|noise|seed/i,[/seed|noise_seed/i]);const durationNode=nodeFor(profile.mappings.duration);const directFrames=/length|frame/i.test(profile.mappings.duration.input_name)&&!/float|duration/i.test(`${durationNode?.class_type||''} ${durationNode?.title||''}`);profile.mappings.duration_mode=directFrames?'frames':'seconds';profile.mappings.frame_divisor=directFrames?17:1;profile.mappings.frame_remainder=directFrames?5:0;const output=[...nodes.value].reverse().find(node=>/save|videocombine/i.test(`${node.title} ${node.class_type}`))||[...nodes.value].reverse().find(node=>/combine|createvideo/i.test(`${node.title} ${node.class_type}`));profile.mappings.output_node_id=output?.id||''}
async function importWorkflow(event){clearNotice();const file=event.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text());const info=summarize(parsed);workflow.value=info.graph;nodes.value=info.list;workflowFile.value=file.name;if(!profile.name)profile.name=file.name.replace(/\.json$/i,'');autoMap();message.value=`已读取 ${nodes.value.length} 个节点，请核对自动映射后保存。`}catch(e){workflow.value=null;nodes.value=[];error.value=e.message}finally{event.target.value=''}}
async function captureLatest(){busy.value=true;clearNotice();try{const data=await requestJSON('/api/comfyui/capture-latest',{method:'POST'});workflow.value=data.workflow;nodes.value=data.nodes||[];workflowFile.value=`ComfyUI 最近任务 ${data.prompt_id}`;if(!profile.name)profile.name='ComfyUI 最近工作流';autoMap();message.value=`已从 ComfyUI 最近一次任务读取 ${nodes.value.length} 个节点，请核对映射。`}catch(e){error.value=e.message}finally{busy.value=false}}
function nodeFor(binding){return nodes.value.find(node=>node.id===String(binding.node_id))}
function inputsFor(binding){return nodeFor(binding)?.inputs||[]}
function normalizeBinding(binding){if(!nodes.value.some(node=>node.id===String(binding.node_id))){binding.node_id='';binding.input_name='';return}if(!inputsFor(binding).includes(binding.input_name))binding.input_name=inputsFor(binding)[0]||''}
async function editProfile(id){busy.value=true;creatingProfile.value=false;clearNotice();try{const data=await requestJSON('/api/comfyui/profiles/'+encodeURIComponent(id));workflow.value=data.workflow;nodes.value=data.nodes||[];profile.id=data.id;profile.name=data.name;profile.kind=data.kind;profile.default_width=data.default_width||1280;profile.default_height=data.default_height||720;profile.resolution_preset=data.resolution_preset||inferResolutionPreset(profile.default_width,profile.default_height);profile.default_seed=Number.isInteger(data.default_seed)?data.default_seed:-1;Object.assign(profile.mappings,data.mappings||{});workflowFile.value='已保存的工作流'}catch(e){error.value=e.message}finally{busy.value=false}}
async function saveProfile(){if(!workflow.value){error.value='请先导入 API 格式工作流。';return}busy.value=true;clearNotice();try{const saved=await requestJSON('/api/comfyui/profiles',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:profile.id,name:profile.name,kind:profile.kind,workflow:workflow.value,mappings:profile.mappings,resolution_preset:profile.kind==='video'?profile.resolution_preset:'custom',default_width:profile.default_width,default_height:profile.default_height,default_seed:profile.default_seed})});await load();run.profile_id=saved.id;await editProfile(saved.id);message.value='工作流预设已保存并通过节点检查。'}catch(e){error.value=e.message}finally{busy.value=false}}
async function removeProfile(id){if(!confirm('删除这个工作流预设？原始 ComfyUI 工作流不会被删除。'))return;clearNotice();try{await requestJSON('/api/comfyui/profiles/'+encodeURIComponent(id),{method:'DELETE'});if(run.profile_id===id)run.profile_id='';resetProfile();await load();message.value='预设已删除。'}catch(e){error.value=e.message}}
function chooseReference(event){reference.value=event.target.files?.[0]||null}
function chooseReferenceAudio(event){referenceAudio.value=event.target.files?.[0]||null}
async function start(){clearNotice();if(!run.profile_id){error.value='请先选择工作流预设。';return}busy.value=true;try{const data=new FormData();for(const [key,value] of Object.entries(run))data.append(key,String(value));if(reference.value)data.append('reference',reference.value);if(referenceAudio.value)data.append('reference_audio',referenceAudio.value);job.value=await requestJSON('/api/comfyui/jobs',{method:'POST',body:data});poll()}catch(e){error.value=e.message}finally{busy.value=false}}
function poll(){clearTimeout(pollTimer);if(!job.value?.id)return;pollTimer=setTimeout(async()=>{try{job.value=await requestJSON('/api/comfyui/jobs/'+job.value.id);if(job.value.status==='running')poll()}catch(e){error.value=e.message}},1500)}
async function interrupt(){if(!confirm('这会终止当前 ComfyUI 实例正在执行的任务，是否继续？'))return;try{await requestJSON('/api/comfyui/interrupt',{method:'POST'});message.value='已向 ComfyUI 发送终止请求。'}catch(e){error.value=e.message}}
onMounted(load);onBeforeUnmount(()=>clearTimeout(pollTimer))
</script>

<template>
 <section class="comfy-workbench content">
  <div class="page-heading"><div><p class="eyebrow">COMFYUI BRIDGE</p><h1>ComfyUI 工作台</h1><p class="muted">连接任意可信的 ComfyUI，把固定工作流收束成简单参数，并供 OCV 图片与动态视频使用。</p></div><span class="status-chip" :class="{ready:message.includes('连接成功')}">{{loading?'读取中…':profiles.length+' 个工作流预设'}}</span></div>
  <article class="panel connection-panel">
   <div class="panel-head"><div><h2>连接配置</h2><p class="muted">地址不会写死；本机、局域网和远程 ComfyUI 可以分别配置。</p></div><div class="actions"><button type="button" :disabled="testing" @click="testConnection">{{testing?'检测中…':'测试连接'}}</button><button class="primary" type="button" :disabled="busy" @click="saveConnection">保存连接</button></div></div>
   <div class="form-grid"><label><span>连接名称</span><input v-model.trim="connection.name"></label><label><span>ComfyUI 地址</span><input v-model.trim="connection.base_url" type="url" placeholder="http://127.0.0.1:8188"></label></div>
   <details><summary>高级连接设置</summary><div class="form-grid advanced"><label><span>WebSocket 地址（留空自动推导）</span><input v-model.trim="connection.websocket_url" placeholder="ws://127.0.0.1:8188/ws"></label><label><span>提交路径</span><input v-model.trim="connection.prompt_path"></label><label><span>历史查询路径</span><input v-model.trim="connection.history_path"></label><label><span>素材上传路径</span><input v-model.trim="connection.upload_path"></label><label><span>结果读取路径</span><input v-model.trim="connection.view_path"></label><label><span>终止路径</span><input v-model.trim="connection.interrupt_path"></label></div></details>
  </article>

  <div class="workbench-grid">
   <article class="panel profile-list"><div class="panel-head"><div><h2>工作流预设</h2><p class="muted">连接配置和工作流分开保存，换机器不必重做节点映射。</p></div><button type="button" @click="newProfile">＋ 新预设</button></div><button v-for="item in profiles" :key="item.id" type="button" class="profile-row" :class="{active:profile.id===item.id}" @click="editProfile(item.id)"><span><b>{{item.name}}</b><small>{{({image:'跑图',video:'跑视频',upscale:'放大',custom:'自定义'})[item.kind]}} · {{item.nodes?.length||0}} 个节点</small></span><i @click.stop="removeProfile(item.id)">删除</i></button><p v-if="!profiles.length" class="empty">尚无预设。点击“新预设”开始配置。</p></article>
   <article ref="mappingPanel" class="panel mapping-panel" :class="{'creating-profile':creatingProfile}"><div class="panel-head"><div><h2>{{creatingProfile?'新建工作流预设':'参数映射'}}</h2><p class="muted">{{creatingProfile?'先读取最近一次运行，或导入一份 API 工作流。':'工作流内部可以继续修改；只要这些槽位有效，OCV 就能继续调用。'}}</p></div><div class="actions"><button type="button" :disabled="busy" @click="captureLatest">读取最近一次运行</button><label class="file-button">导入 API 工作流<input type="file" accept=".json,application/json" @change="importWorkflow"></label></div></div>
    <div class="form-grid"><label><span>预设名称</span><input ref="profileNameInput" v-model.trim="profile.name" placeholder="例如 H3 · Self-Lift"></label><label><span>用途</span><select v-model="profile.kind"><option value="video">跑视频</option><option value="image">跑图</option><option value="upscale">放大</option><option value="custom">自定义</option></select></label><label v-if="profile.kind==='video'"><span>输出分辨率</span><select v-model="profile.resolution_preset" @change="applyResolutionPreset"><option value="480p">480P（快速）</option><option value="720p">720P（推荐）</option><option value="1080p">1080P（高清）</option><option value="custom">自定义</option></select></label><label v-if="profile.kind==='video'&&profile.resolution_preset!=='custom'"><span>横竖屏自动尺寸</span><input :value="resolutionSummary" readonly></label><label v-if="profile.kind!=='video'||profile.resolution_preset==='custom'"><span>默认宽度</span><input v-model.number="profile.default_width" type="number" min="32" max="8192" step="2"></label><label v-if="profile.kind!=='video'||profile.resolution_preset==='custom'"><span>默认高度</span><input v-model.number="profile.default_height" type="number" min="32" max="8192" step="2"></label><label><span>默认 Seed（-1 随机）</span><input v-model.number="profile.default_seed" type="number" min="-1"></label></div><div v-if="creatingProfile&&!workflow" class="new-profile-guide"><b>新预设尚未绑定工作流</b><span>推荐点击“读取最近一次运行”，OCV 会读取你刚在 ComfyUI 中成功运行的节点图。</span></div><p class="workflow-file">{{workflowFile||'尚未导入工作流'}}</p>
    <div v-if="nodes.length" class="mapping-list"><div v-for="field in [{key:'prompt',label:'提示词'},{key:'image',label:'参考图'},{key:'audio',label:'参考音频'},{key:'duration',label:'时长 / 帧数'},{key:'width',label:'宽度'},{key:'height',label:'高度'},{key:'seed',label:'Seed'}]" :key="field.key" class="mapping-row"><b>{{field.label}}</b><select v-model="profile.mappings[field.key].node_id" @change="normalizeBinding(profile.mappings[field.key])"><option value="">不映射</option><option v-for="node in nodes" :key="node.id" :value="node.id">#{{node.id}} · {{node.title}}</option></select><select v-model="profile.mappings[field.key].input_name" :disabled="!profile.mappings[field.key].node_id"><option value="">选择输入</option><option v-for="input in inputsFor(profile.mappings[field.key])" :key="input" :value="input">{{input}}</option></select></div><div class="mapping-row"><b>结果输出</b><select v-model="profile.mappings.output_node_id"><option value="">自动寻找</option><option v-for="node in nodes" :key="node.id" :value="node.id">#{{node.id}} · {{node.title}}</option></select><span></span></div></div>
    <div v-if="profile.mappings.duration.node_id" class="duration-rule"><label><span>传入方式</span><select v-model="profile.mappings.duration_mode"><option value="seconds">秒数</option><option value="frames">换算帧数</option></select></label><template v-if="profile.mappings.duration_mode==='frames'"><label><span>FPS</span><input v-model.number="profile.mappings.fps" type="number" min="1"></label><label><span>帧数整除基数</span><input v-model.number="profile.mappings.frame_divisor" type="number" min="1"></label><label><span>允许余数</span><input v-model.number="profile.mappings.frame_remainder" type="number" min="0"></label></template></div>
    <div class="actions"><button type="button" :disabled="!nodes.length" @click="autoMap">重新自动识别</button><button class="primary" type="button" :disabled="busy||!workflow||!profile.name" @click="saveProfile">保存并检查映射</button></div>
   </article>
  </div>

  <article class="panel runner"><div class="panel-head"><div><h2>试跑与预览</h2><p class="muted">这里只运行一次工作流，不会修改 OCV 项目。</p></div><button v-if="job?.status==='running'" type="button" @click="interrupt">紧急终止</button></div>
   <div class="form-grid"><label><span>工作流预设</span><select v-model="run.profile_id"><option value="">请选择</option><option v-for="item in profiles" :key="item.id" :value="item.id">{{item.name}}</option></select></label><label><span>参考图</span><input type="file" accept="image/png,image/jpeg,image/webp" @change="chooseReference"></label><label><span>参考音频</span><input type="file" accept="audio/wav,audio/mpeg,audio/flac,audio/mp4,audio/ogg" @change="chooseReferenceAudio"></label><label><span>时长（秒）</span><input v-model.number="run.duration" type="number" min="0.1" step="0.1"></label><label><span>宽 × 高</span><span class="inline-size"><input v-model.number="run.width" type="number" min="32" step="32"><i>×</i><input v-model.number="run.height" type="number" min="32" step="32"></span></label><label><span>Seed（-1 随机）</span><input v-model.number="run.seed" type="number" min="-1"></label></div>
   <label class="prompt-field"><span>提示词</span><textarea v-model="run.prompt" rows="5" placeholder="输入本次生成提示词"></textarea></label><div class="actions"><button class="primary" type="button" :disabled="busy||job?.status==='running'||!selectedProfile" @click="start">提交到 ComfyUI</button><span v-if="job" class="job-state" :class="job.status">{{job.message}} · {{job.progress||0}}%</span></div>
   <div v-if="job?.result_url" class="result"><video v-if="selectedProfile?.kind==='video'" :src="job.result_url" controls></video><img v-else :src="job.result_url" alt="ComfyUI 生成结果"></div>
  </article>
  <p v-if="message" class="notice success">{{message}}</p><p v-if="error" class="notice error">{{error}}</p>
 </section>
</template>

<style scoped>
.comfy-workbench{display:grid;gap:20px}.panel{border:1px solid var(--border,#34403e);background:var(--panel,#1c2221);border-radius:12px;padding:22px}.panel-head,.actions{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.panel-head h2{margin:0 0 5px}.panel-head p{margin:0}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}.form-grid label,.prompt-field,.duration-rule label{display:grid;gap:6px;font-size:12px}.advanced{padding-top:0}.connection-panel details{margin-top:14px}.connection-panel summary{cursor:pointer;color:var(--muted,#9aaba5)}.workbench-grid{display:grid;grid-template-columns:minmax(240px,.35fr) minmax(0,1fr);gap:20px}.profile-list{align-self:start}.profile-row{display:flex;width:100%;justify-content:space-between;align-items:center;text-align:left;margin-top:9px;padding:12px;background:transparent}.profile-row.active{border-color:var(--accent,#83dec5);background:#25342f}.profile-row span{display:grid;gap:4px}.profile-row small{color:var(--muted,#9aaba5)}.profile-row i{font-style:normal;font-size:11px;color:#c99}.file-button{cursor:pointer;border:1px solid var(--border,#34403e);border-radius:8px;padding:9px 12px}.file-button input{display:none}.mapping-panel.creating-profile{border-color:var(--accent,#83dec5);box-shadow:0 0 0 2px color-mix(in srgb,var(--accent,#83dec5) 16%,transparent)}.new-profile-guide{display:grid;gap:5px;margin-top:14px;padding:13px 15px;border:1px dashed var(--accent,#83dec5);border-radius:9px;background:#20302b;color:var(--muted,#9aaba5);font-size:12px}.new-profile-guide b{color:var(--accent,#83dec5)}.workflow-file{font-size:12px;color:var(--muted,#9aaba5)}.mapping-list{display:grid;gap:8px;margin:16px 0}.mapping-row{display:grid;grid-template-columns:90px minmax(180px,1fr) minmax(130px,.65fr);gap:9px;align-items:center}.mapping-row b{font-size:12px}.duration-rule{display:flex;gap:12px;align-items:end;flex-wrap:wrap;padding:13px;border:1px solid var(--border,#34403e);border-radius:9px;margin-bottom:15px}.duration-rule label{min-width:110px}.inline-size{display:flex;align-items:center;gap:6px}.inline-size input{width:100%}.inline-size i{font-style:normal}.prompt-field{margin:15px 0}.job-state{font-size:12px}.job-state.completed{color:#83dec5}.job-state.failed,.notice.error{color:#e6a08d}.result{margin-top:18px;display:flex;justify-content:center;background:#101413;border-radius:10px;overflow:hidden}.result video,.result img{max-width:100%;max-height:680px}.notice{position:sticky;bottom:18px;padding:12px 15px;border-radius:8px;background:#26332f;border:1px solid var(--border,#34403e);margin:0}.notice.success{color:#83dec5}.status-chip{padding:6px 10px;border-radius:99px;background:#2f3329;color:#d7c68d}.status-chip.ready{background:#243a32;color:#83dec5}
@media(max-width:900px){.workbench-grid{grid-template-columns:1fr}.form-grid{grid-template-columns:1fr}.mapping-row{grid-template-columns:1fr}.profile-list{align-self:stretch}}
</style>
